apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: test-secret  # Name of the Kubernetes secret to create
  data:
  - secretKey: password  # Key in the Kubernetes secret
    remoteRef:
      key: testSecret
      property: markus # Path to your Vault secret (adjust path as needed)