apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    fullnameOverride: external-secrets-operator
#    serviceMonitor:
#      enabled: true