---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak-operator
      version: "19.0.1"
      sourceRef:
        kind: HelmRepository
        name: keycloak-operator
        namespace: flux-system
  values:
    # Add any custom values here
    # For example:
    # image:
    #   tag: "21.1.1"
    # replicas: 1