---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-secret
  namespace: default
spec:
  encryptedData:
    password: <base64-encoded-password>
  template:
    metadata:
      name: example-secret
      namespace: default
    type: Opaque