---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets/sealed-secrets
      version: "2.17.9"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-systemd